PROGRAM spag_program_1
   use test_problems

!*********************************************************************
!
!
!      TESTPROGRAM FOR NLPQLP USING THE PROBLEMS DESCRIBED IN:
!
!      W. Hock, K. Schittkowski, 'Test Examples for Nonlinear
!      Programming Codes', Lecture Notes in Economics and Mathematical
!      Systems, Springer, No, 187, 1981
!
!      K. Schittkowski, 'More Test Examples for Nonlinear Programming
!      Codes', Lecture Notes in Economics and Mathematical Systems,
!      Springer, No, 282, 1987
!
!
!
!      Purpose:
!      -------
!
!      The 306 test problems of the two mentioned collections are executed
!      within a loop. A decision is made which of the test runs is considered
!      to be successful, and performance results are evaluated.
!
!      It is possible to add random errors to function values and to evaluate
!      derivatives by three different approximation formulae.
!
!
!
!      Output:
!      ------
!
!      Four files are generated by the test program, one for individual results
!      (TEST.DAT), one for a Latex table (TEST.TEX), another one for final
!      performance results in 'readable' form (RESULT.DAT), and a file with
!      numerical performance data in one line (TEMP.DAT).
!
!      a) TEST.DAT:
!
!      Typical contants of TEST.DAT without lines generated by the NLP routine:
!
!      TP 1 2 0 0 0 26  19 102  0.73115910D-10  0.000D+00  0.000D+00
!      TP 2 2 0 0 0 20  15  80  0.50426193D-01  0.106D-06  0.000D+00
!      TP 3 2 0 0 0 10  10  50  0.38971022D-21  0.106D-06  0.000D+00
!      TP 4 2 0 0 0  2   2  10  0.26666667D+01  0.000D+00  0.000D+00
!      TP 5 2 0 0 0  8   6  32 -0.19132230D+01  0.109D-10  0.000D+00
!      TP  ...............
!
!      The following data are listed:
!
!       1.  NTP      (Test problem number)
!       2.  N        (Number of variables)
!       3.  ME       (Number of equality constraints)
!       4.  M        (Number of constraints)
!       5.  IFAIL    (Convergence criterion)
!       6.  NF       (Number of objective function evaluations)
!       7.  NDF      (Number of gradient evaluations of objective function)
!       8.  NEF      (Number of equivalent function evaluations, i.e. NF plus
!                     number of function calls needed for gradient approximation)
!       9.  FEX      (Exact objective function value)
!      10.  F        (Cmputed objective function value)
!      11.  DFX      (Relative error in objective function)
!      12.  DGX      (Sum of constraint violations including bound violations)
!
!
!      b) TEST.TEX:
!
!      Same with Latex separators
!
!
!      c) RESULT.DAT:
!
!      The following summary is listed:
!
!      Tolerance for gradient approximation
!      Termination accuracy for NLP routine
!      Total number of test runs
!      Number of successful test runs
!      - constraint violation less than squared tolerance and
!        either error in objective less than tolerance or
!        termination criteria of NLP routine satisfied
!      Number of better test runs
!      - constraint violation less than squared tolerance and
!        error in objective less than -tolerance
!      Number of local solutions obtained
!      Number of runs without satisfying termination accuracy
!      - as indicated by NLP routine, i.e. IFAIL>0
!      Tolerance for determining successful return
!      Average number of function evaluations
!      Average number of gradient evaluations
!      Average number of equivalent function calls
!      - additionlly counted function calls for gradient
!        approximations
!
!
!      d) TEMP.DAT:
!
!      Contains more or less the same data in one row, e.g.
!
!     0.1D-07 0.1D-06 0.1D-12 0.4D-42 306   0  44  22 322 285  21
!
!
!
!      Compilation and Link:
!      --------------------
!
!      To run the code, the following files must be linked:
!
!      TESTP.OBJ    : test program
!      PROB.OBJ     : 306 test problems
!      CONV.OBJ     : interface for executing individual test problems
!      NLPQLP.OBJ   : nonlinear programming code
!      QL.OBJ       : auxiliary routine called by NLPQLP
!
!
!
!      Version:
!      -------
!
!      1.0   June 2001
!      2.0   April 2008
!      3.0   November 2009
!      4.0   February 2010
!      5.0   April 2010
!      6.0   February 20011
!
!
!
!      Author (C):
!      ----------
!
!      Prof. K. Schittkowski,
!      Dept. of Computer Science,
!      University of Bayreuth,
!      D-95440 Bayreuth,
!      Germany
!
!
!
!      Reference:
!      ---------
!
!      K. Schittkowski. NLPQL: A Fortran subroutine solving
!      constrained nonlinear programming problems, Annals of
!      Operations Research, Vol.5 (1985/6), 485-500.
!
!      K. Schittkowski. NLPQLP: A Fortran implementation
!      of a sequential quadratic programming algorithm with
!      distributed and non-monotone line search, Report,
!      Department of Computer Science, University of Bayreuth,
!      2006
!
!*********************************************************************

   IMPLICIT NONE
   INTEGER NMAX , MMAX , LMAX , MNNMAX , LWA , LIWA , LACTIV , N , Nili , Ninl , Neli , Nenl , Nex
   PARAMETER (NMAX=101,MMAX=50,LMAX=1,MNNMAX=NMAX+NMAX+MMAX+2,LWA=3*NMAX*NMAX/2+33*NMAX+10*MMAX+150,LIWA=MMAX+NMAX+150,            &
            & LACTIV=2*MMAX+15)
   COMMON /l1    / N , Nili , Ninl , Neli , Nenl/l2    / Xtp(NMAX)/l3    / Gtp(MMAX)/l4    / Dftp(NMAX)/l5    / Dgtp(NMAX*MMAX)    &
                 & /l6    / Fxtp/l8    / Ntp/l9    / Index1(MMAX)/l10   / Index2(MMAX)/l11   / Lxl(NMAX)/l12   / Lxu(NMAX)         &
                 & /l13   / Xl(NMAX)/l14   / Xu(NMAX)/l20   / Lex , Nex , Fex , Xex(NMAX)
   LOGICAL Index1 , Index2 , Lxl , Lxu , Lex
   REAL*8 Xtp , Gtp , Dftp , Dgtp , Fxtp , Xl , Xu , Fex , Xex
   DIMENSION f(LMAX) , x(NMAX,LMAX) , g(MMAX,LMAX) , geps(MMAX) , df(NMAX) , dg(MMAX,NMAX) , u(MNNMAX) , c(NMAX,NMAX) , d(NMAX) ,  &
           & wa(LWA) , iwa(LIWA) , active(LACTIV)
   REAL*8 x , f , g , df , dg , u , c , d , acc , accqp , stpmin , wa , dgx , dfx , dfx1 , epssucc , rhob , geps , Epsgrd
   LOGICAL active
   INTEGER notot , nofail , nosucc , nftot , ndftot , neftot , noex , noexgt , ndfequ , nobett , iout1 , iout2 , iout3 , iout4 ,   &
         & i , j , l , iprint , maxfun , maxit , mode , maxnm , ntpa , ntpe , Ntp , mnn2 , nf , ndf , ifail , me , mi , m , iwa
   COMMON /testr / Epsgrd

   external :: nlpqlp, ql
   INTEGER :: spag_nextblock_1

   spag_nextblock_1 = 1
   SPAG_DispatchLoop_1: DO
      SELECT CASE (spag_nextblock_1)
      CASE (1)
         !
         !   Open output files
         !
         iout1 = 61
         iout2 = 62
         iout3 = 63
         iout4 = 64
         OPEN (iout1,FILE='TEST.DAT',STATUS='UNKNOWN')
         OPEN (iout2,FILE='TEMP.DAT',STATUS='UNKNOWN')
         OPEN (iout3,FILE='RESULT.DAT',STATUS='UNKNOWN')
         OPEN (iout4,FILE='TEST.TEX',STATUS='UNKNOWN')
         !
         !   Tolerances for calling optimization routine
         !
         iprint = 2
         maxfun = 30
         maxit = 3000
         mode = 0
         maxnm = 30
         rhob = 1.0D4
         l = 1
         stpmin = 1.0D-10
         acc = 1.0D-7
         accqp = 1.0D-13
         epssucc = 0.01D0
         Epsgrd = 1.0D-8
         !
         !   Initializing counters
         !
         notot = 0
         nofail = 0
         nosucc = 0
         nftot = 0
         ndftot = 0
         neftot = 0
         noex = 0
         noexgt = 0
         nobett = 0
         !
         !   Initial data for executing test problems in a loop
         !
         ntpa = 1
         ntpe = 395
         Ntp = ntpa
         spag_nextblock_1 = 2
      CASE (2)
         !
         !   Some test problem numbers do not exist
         !
         IF ( .NOT.(Ntp==58 .OR. Ntp==82 .OR. Ntp==94 .OR. Ntp==115 .OR. (Ntp>119 .AND. Ntp<200) .OR. Ntp==306 .OR. Ntp==313 .OR.  &
            & Ntp==349 .OR. Ntp==363 .OR. Ntp==390) ) THEN
            !
            !   Initialize test problem
            !
            CALL conv(1)
            me = Neli + Nenl
            mi = Nili + Ninl
            m = me + mi
            DO i = 1 , N
               x(i,1) = Xtp(i)
               IF ( .NOT.Lxl(i) ) Xl(i) = x(i,1) - 1.0D+5
               IF ( .NOT.Lxu(i) ) Xu(i) = x(i,1) + 1.0D+5
               IF ( x(i,1)<Xl(i) ) x(i,1) = Xl(i)
               IF ( x(i,1)>Xu(i) ) x(i,1) = Xu(i)
            ENDDO
            mnn2 = m + N + N + 2
            DO j = 1 , m
               Index1(j) = .TRUE.
            ENDDO
            !
            ! ----------------------------------------------------------------------
            !   Beginn of optimization block (reverse communication)
            !
            nf = 0
            ndf = 0
            ifail = 0
            DO j = 1 , m
               active(j) = .TRUE.
            ENDDO
            SPAG_Loop_1_1: DO
               IF ( ifail==-1 .OR. ifail==0 ) THEN
                  nf = nf + 1
                  CALL nlfunc(m,me,N,f(1),g,x)
               ENDIF
               IF ( ifail==-2 .OR. ifail==0 ) THEN
                  ndf = ndf + 1
                  CALL nlgrad(m,me,MMAX,N,f(1),g,df,dg,x,geps)
               ENDIF
               CALL nlpqlp(l,m,me,MMAX,N,NMAX,mnn2,x,f,g,df,dg,u,Xl,Xu,c,d,acc,accqp,&
                           stpmin,maxfun,maxit,maxnm,rhob,iprint,mode,   &
                           iout1,ifail,wa,LWA,iwa,LIWA,active,LACTIV,.TRUE.,ql)
               IF ( ifail>=0 ) THEN
                  !
                  !   End of optimization block
                  ! ----------------------------------------------------------------------
                  !
                  !   Evaluate results
                  !
                  dfx = f(1) - Fex
                  dfx1 = dfx
                  IF ( Fex/=0.0D0 ) dfx1 = dfx/dabs(Fex)
                  dgx = 0.0D+0
                  DO j = 1 , m
                     IF ( j<=me .OR. g(j,1)<0.0D+0 ) dgx = dmax1(dgx,dabs(g(j,1)))
                  ENDDO
                  DO i = 1 , N
                     IF ( x(i,1)<Xl(i) ) dgx = dgx + Xl(i) - x(i,1)
                     IF ( x(i,1)>Xu(i) ) dgx = dgx + x(i,1) - Xu(i)
                  ENDDO
                  nftot = nftot + nf
                  ndftot = ndftot + ndf
                  ndfequ = nf + N*ndf
                  neftot = neftot + ndfequ
                  WRITE (iout1,99001) Ntp , N , me , m , ifail , nf , ndf , ndfequ , Fex , f(1) , dfx1 , dgx
!
99001             FORMAT ('TP',5I4,3I8,2D16.8,2D11.3)
                  WRITE (iout4,99005) Ntp , N , me , m , ifail , nf , ndf , ndfequ , Fex , f(1) , dfx1 , dgx
99005             FORMAT (I4,' &',I4,' &',I4,' &',I4,' &',I4,' &',I8,'& ',I8,' &',I8,' &',E16.8,' &',E16.8,' &',E11.2,' &',E11.2,  &
                         &' \\')
                  IF ( dfx1<epssucc .AND. dgx<epssucc**2 ) THEN
                     nosucc = nosucc + 1
                     noex = noex + 1
                     IF ( dfx1<-epssucc ) THEN
                        WRITE (iout3,99008) Ntp
99008                   FORMAT (' *** Better solution: TP',I3)
                        nobett = nobett + 1
                     ENDIF
                  ELSEIF ( ifail==0 .AND. dgx<epssucc**2 .AND. dfx1>=epssucc ) THEN
                     nosucc = nosucc + 1
                     noexgt = noexgt + 1
                     WRITE (iout3,99006) Ntp
99006                FORMAT (' *** Local solution:  TP',I3)
                  ELSE
                     nofail = nofail + 1
                     WRITE (iout3,99007) Ntp
99007                FORMAT (' *** False solution:  TP',I3)
                  ENDIF
                  IF ( ifail>0 ) WRITE (iout3,99009) ifail , Ntp
99009             FORMAT (' *** Message IFAIL=',I4,': TP',I3)
                  notot = notot + 1
                  EXIT SPAG_Loop_1_1
               ENDIF
            ENDDO SPAG_Loop_1_1
         ENDIF
!
!   Next problem
!
         Ntp = Ntp + 1
         IF ( Ntp<=ntpe ) THEN
            spag_nextblock_1 = 2
            CYCLE SPAG_DispatchLoop_1
         ENDIF
         IF ( nosucc>0 ) WRITE (iout2,99002) Epsgrd , acc , accqp , notot , nosucc , nofail , int(dble(nftot/nosucc)) ,            &
                              & int(dble(ndftot/nosucc)) , int(dble(neftot/nosucc)) , noex , noexgt
99002    FORMAT (3X,4D8.1,8I6,E10.2)
         IF ( nosucc>0 ) WRITE (iout3,99003) Epsgrd , acc , notot , nosucc , nobett , noexgt , nofail , epssucc
99003    FORMAT (//,' *** NUMERICAL RESULTS ***',///,' Tolerance for gradient approximation:           ',D14.1,//,                 &
                &' Termination accuracy for NLP routine:           ',D14.1,//,' Total number of test runs:                      ', &
               & I14,//,' Number of successful test runs:                 ',I14,/,                                                 &
                &' - constraint violation less than squared tolerance and',/,'   either error in objective less than tolerance or',&
               & /,'   termination criteria of NLP routine satisfied',//,' Number of better test runs:                     ',I14,/,&
                &' - constraint violation less than squared tolerance and',/,'   error in objective less than -tolerance',//,      &
                &' Number of local solutions obtained:             ',I14,//,                                                       &
                &' Number of runs without satisfying termination accuracy:',I7,/,' - as indicated by NLP routine, i.e. IFAIL>0',//,&
                &' Tolerance for determining successful return:    ',D14.1)
         IF ( nosucc>0 ) WRITE (iout3,99004) int(dble(nftot/nosucc)) , int(dble(ndftot/nosucc)) , int(dble(neftot/nosucc))
99004    FORMAT (//,' Average number of function evaluations:         ',I14,/,' - NLFUNC calls for successful returns',//,         &
                &' Average number of gradient evaluations:         ',I14,/,' - NLGRAD calls for successful returns',//,            &
                &' Average number of equivalent function calls     ',I14,/,' - additionlly counted function calls for gradient ',  &
                &'approximations',//)
         CLOSE (iout1)
         CLOSE (iout2)
         CLOSE (iout3)
         CLOSE (iout4)
         EXIT SPAG_DispatchLoop_1
      END SELECT
   ENDDO SPAG_DispatchLoop_1
!
!   End of test program
!

   contains 

   SUBROUTINE nlfunc(M,Me,N,F,G,X)
      !
      !********************************************************************
      !
      !   Evaluation of test problem functions
      !
      !*********************************************************************
      !
         IMPLICIT NONE
         INTEGER NMAX , MMAX
         PARAMETER (NMAX=101,MMAX=50)
         COMMON /l1    / Ntp , Nili , Ninl , Neli , Nenl/l2    / Xtp(NMAX)/l3    / Gtp(MMAX)/l4    / Dftp(NMAX)/l5    / Dgtp(NMAX*MMAX)  &
                       & /l6    / Fxtp/l9    / Index1(MMAX)/l10   / Index2(MMAX)/l11   / Lxl(NMAX)/l12   / Lxu(NMAX)/l13   / Xl(NMAX)    &
                       & /l14   / Xu(NMAX)
         LOGICAL Index1 , Index2 , Lxl , Lxu
         INTEGER M , Me , N , Ntp , Nili , Ninl , Neli , Nenl , i , j
         REAL*8 Xtp , Gtp , Dftp , Dgtp , Fxtp , Xl , Xu , F , G(M) , X(N)
      !
         DO i = 1 , N
            Xtp(i) = X(i)
         ENDDO
         CALL conv(2)
         F = Fxtp
         IF ( M==0 ) RETURN
         DO j = 1 , M
            Index1(j) = .TRUE.
         ENDDO
         CALL conv(4)
         IF ( Me/=0 ) THEN
            DO j = 1 , Me
               G(j) = Gtp(j+M-Me)
            ENDDO
         ENDIF
         IF ( Me==M ) RETURN
         DO j = Me + 1 , M
            G(j) = Gtp(j-Me)
         ENDDO
      !
      !   End of function evaluation
      !
      END SUBROUTINE nlfunc
      SUBROUTINE nlgrad(M,Me,Mmax,N,F,G,Df,Dg,X,Geps)
      !
      !*********************************************************************
      !
      !   Gradient evaluation by differnce formulae
      !
      !*********************************************************************
      !
         IMPLICIT NONE
         REAL*8 F , G(Mmax) , X(N) , Df(N) , Dg(Mmax,N) , Geps(Mmax)
         INTEGER M , Me , Mmax , N , i , j
         REAL*8 epsi , epsa , feps , xold , ufl
         COMMON /testr / Epsgrd
         REAL*8 Epsgrd
      !
         ufl = dsqrt(dsqrt(Epsgrd))
      !
      !   One-sided differences
      !
         DO i = 1 , N
            xold = X(i)
            epsa = Epsgrd*dmax1(ufl,dabs(X(i)))
            epsi = 1.0D0/epsa
            X(i) = X(i) + epsa
            CALL nlfunc(M,Me,N,feps,Geps,X)
            Df(i) = epsi*(feps-F)
            DO j = 1 , M
               Dg(j,i) = epsi*(Geps(j)-G(j))
            ENDDO
            X(i) = xold
         ENDDO
      !
      !   End of gradient evaluation
      !
      END SUBROUTINE nlgrad
      !      

END PROGRAM spag_program_1
